name: angular_recaptcha
description: Google Angular Recaptcha
version: 0.1.4
homepage: https://github.com/lejard-h/angular_recaptcha

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  angular: ^5.0.0
  angular_forms: ^2.0.0
  js: ^0.6.0
  dart_browser_loader: ^0.0.3
